/* calculator.h generated by valac 0.48.9, the Vala compiler, do not modify */

#ifndef __CALCULATOR_H__
#define __CALCULATOR_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

G_BEGIN_DECLS

#define TYPE_MY_CALC (my_calc_get_type ())
#define MY_CALC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_CALC, MyCalc))
#define MY_CALC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_CALC, MyCalcClass))
#define IS_MY_CALC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_CALC))
#define IS_MY_CALC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_CALC))
#define MY_CALC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_CALC, MyCalcClass))

typedef struct _MyCalc MyCalc;
typedef struct _MyCalcClass MyCalcClass;
typedef struct _MyCalcPrivate MyCalcPrivate;

struct _MyCalc {
	GtkWindow parent_instance;
	MyCalcPrivate * priv;
};

struct _MyCalcClass {
	GtkWindowClass parent_class;
};

GType my_calc_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyCalc, g_object_unref)
MyCalc* my_calc_new (void);
MyCalc* my_calc_construct (GType object_type);
gint _vala_main (gchar** args,
                 gint args_length1);

G_END_DECLS

#endif
