/* calculator-1.0.vapi generated by valac 0.48.9, do not modify. */

[CCode (cheader_filename = "calculator.h")]
public class MyCalc : Gtk.Window {
	public MyCalc ();
}
[CCode (cheader_filename = "calculator.h")]
public static int main (string[] args);
