/* vala-calculator.c generated by valac 0.48.9, the Vala compiler
 * generated from vala-calculator.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>

#define TYPE_MY_CALC (my_calc_get_type ())
#define MY_CALC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MY_CALC, MyCalc))
#define MY_CALC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MY_CALC, MyCalcClass))
#define IS_MY_CALC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MY_CALC))
#define IS_MY_CALC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MY_CALC))
#define MY_CALC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MY_CALC, MyCalcClass))

typedef struct _MyCalc MyCalc;
typedef struct _MyCalcClass MyCalcClass;
typedef struct _MyCalcPrivate MyCalcPrivate;
enum  {
	MY_CALC_0_PROPERTY,
	MY_CALC_NUM_PROPERTIES
};
static GParamSpec* my_calc_properties[MY_CALC_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _MyCalc {
	GtkWindow parent_instance;
	MyCalcPrivate * priv;
};

struct _MyCalcClass {
	GtkWindowClass parent_class;
};

struct _MyCalcPrivate {
	GtkEntry* entDisp;
	gboolean flag_dot;
	gboolean flag_entrystarted;
	gchar* entry;
	gchar* result;
	gchar* operation;
};

static gint MyCalc_private_offset;
static gpointer my_calc_parent_class = NULL;

GType my_calc_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MyCalc, g_object_unref)
MyCalc* my_calc_new (void);
MyCalc* my_calc_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                        gpointer self);
static void my_calc_doClear (MyCalc* self);
static void my_calc_on_clicked (MyCalc* self,
                         GtkButton* button);
static void _my_calc_on_clicked_gtk_button_clicked (GtkButton* _sender,
                                             gpointer self);
static void my_calc_doApp (MyCalc* self,
                    const gchar* what);
static void my_calc_doOpe (MyCalc* self,
                    const gchar* what);
static void my_calc_doDot (MyCalc* self);
static void my_calc_doSign (MyCalc* self);
static void my_calc_doSqrt (MyCalc* self);
static void my_calc_doEqual (MyCalc* self);
static void my_calc_disp (MyCalc* self,
                   const gchar* what);
static void my_calc_finalize (GObject * obj);
static GType my_calc_get_type_once (void);
gint _vala_main (gchar** args,
                 gint args_length1);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
my_calc_get_instance_private (MyCalc* self)
{
	return G_STRUCT_MEMBER_P (self, MyCalc_private_offset);
}

static void
_gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                   gpointer self)
{
#line 19 "../vala-calculator.vala"
	gtk_main_quit ();
#line 96 "vala-calculator.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 60 "../vala-calculator.vala"
	return self ? g_object_ref (self) : NULL;
#line 104 "vala-calculator.c"
}

static void
_my_calc_on_clicked_gtk_button_clicked (GtkButton* _sender,
                                        gpointer self)
{
#line 65 "../vala-calculator.vala"
	my_calc_on_clicked ((MyCalc*) self, _sender);
#line 113 "vala-calculator.c"
}

MyCalc*
my_calc_construct (GType object_type)
{
	MyCalc * self = NULL;
	GtkEntry* _tmp0_;
	GtkEntry* _tmp1_;
	GtkEntry* _tmp2_;
	GtkButton* but_0 = NULL;
	GtkButton* _tmp3_;
	GtkButton* but_1 = NULL;
	GtkButton* _tmp4_;
	GtkButton* but_2 = NULL;
	GtkButton* _tmp5_;
	GtkButton* but_3 = NULL;
	GtkButton* _tmp6_;
	GtkButton* but_4 = NULL;
	GtkButton* _tmp7_;
	GtkButton* but_5 = NULL;
	GtkButton* _tmp8_;
	GtkButton* but_6 = NULL;
	GtkButton* _tmp9_;
	GtkButton* but_7 = NULL;
	GtkButton* _tmp10_;
	GtkButton* but_8 = NULL;
	GtkButton* _tmp11_;
	GtkButton* but_9 = NULL;
	GtkButton* _tmp12_;
	GtkButton* butDiv = NULL;
	GtkButton* _tmp13_;
	GtkButton* butMul = NULL;
	GtkButton* _tmp14_;
	GtkButton* butMinus = NULL;
	GtkButton* _tmp15_;
	GtkButton* butPlus = NULL;
	GtkButton* _tmp16_;
	GtkButton* butEqual = NULL;
	GtkButton* _tmp17_;
	GtkButton* butPercent = NULL;
	GtkButton* _tmp18_;
	GtkButton* butSqrt = NULL;
	GtkButton* _tmp19_;
	GtkButton* butSign = NULL;
	GtkButton* _tmp20_;
	GtkButton* butCls = NULL;
	GtkButton* _tmp21_;
	GtkButton* butDot = NULL;
	GtkButton* _tmp22_;
	GtkButton** list_button = NULL;
	GtkButton* _tmp23_;
	GtkButton* _tmp24_;
	GtkButton* _tmp25_;
	GtkButton* _tmp26_;
	GtkButton* _tmp27_;
	GtkButton* _tmp28_;
	GtkButton* _tmp29_;
	GtkButton* _tmp30_;
	GtkButton* _tmp31_;
	GtkButton* _tmp32_;
	GtkButton* _tmp33_;
	GtkButton* _tmp34_;
	GtkButton* _tmp35_;
	GtkButton* _tmp36_;
	GtkButton* _tmp37_;
	GtkButton* _tmp38_;
	GtkButton* _tmp39_;
	GtkButton* _tmp40_;
	GtkButton* _tmp41_;
	GtkButton* _tmp42_;
	GtkButton* _tmp43_;
	GtkButton* _tmp44_;
	GtkButton* _tmp45_;
	GtkButton* _tmp46_;
	GtkButton* _tmp47_;
	GtkButton* _tmp48_;
	GtkButton* _tmp49_;
	GtkButton* _tmp50_;
	GtkButton* _tmp51_;
	GtkButton* _tmp52_;
	GtkButton* _tmp53_;
	GtkButton* _tmp54_;
	GtkButton* _tmp55_;
	GtkButton* _tmp56_;
	GtkButton* _tmp57_;
	GtkButton* _tmp58_;
	GtkButton* _tmp59_;
	GtkButton* _tmp60_;
	GtkButton* _tmp61_;
	GtkButton* _tmp62_;
	GtkButton** _tmp63_;
	gint list_button_length1;
	gint _list_button_size_;
	GtkButton** _tmp64_;
	gint _tmp64__length1;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp67_;
	GtkEntry* _tmp68_;
	GtkButton* _tmp69_;
	GtkButton* _tmp70_;
	GtkButton* _tmp71_;
	GtkButton* _tmp72_;
	GtkButton* _tmp73_;
	GtkButton* _tmp74_;
	GtkButton* _tmp75_;
	GtkButton* _tmp76_;
	GtkButton* _tmp77_;
	GtkButton* _tmp78_;
	GtkButton* _tmp79_;
	GtkButton* _tmp80_;
	GtkButton* _tmp81_;
	GtkButton* _tmp82_;
	GtkButton* _tmp83_;
	GtkButton* _tmp84_;
	GtkButton* _tmp85_;
	GtkButton* _tmp86_;
	GtkButton* _tmp87_;
	GtkButton* _tmp88_;
#line 18 "../vala-calculator.vala"
	self = (MyCalc*) g_object_new (object_type, NULL);
#line 19 "../vala-calculator.vala"
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 20 "../vala-calculator.vala"
	gtk_window_set_title ((GtkWindow*) self, "Calculator");
#line 21 "../vala-calculator.vala"
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
#line 22 "../vala-calculator.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 0);
#line 23 "../vala-calculator.vala"
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
#line 26 "../vala-calculator.vala"
	_tmp0_ = self->priv->entDisp;
#line 26 "../vala-calculator.vala"
	gtk_widget_set_can_focus ((GtkWidget*) _tmp0_, FALSE);
#line 27 "../vala-calculator.vala"
	_tmp1_ = self->priv->entDisp;
#line 27 "../vala-calculator.vala"
	g_object_set (_tmp1_, "editable", FALSE, NULL);
#line 28 "../vala-calculator.vala"
	_tmp2_ = self->priv->entDisp;
#line 28 "../vala-calculator.vala"
	gtk_entry_set_alignment (_tmp2_, 1.0f);
#line 29 "../vala-calculator.vala"
	my_calc_doClear (self);
#line 32 "../vala-calculator.vala"
	_tmp3_ = (GtkButton*) gtk_button_new_with_label ("0");
#line 32 "../vala-calculator.vala"
	g_object_ref_sink (_tmp3_);
#line 32 "../vala-calculator.vala"
	but_0 = _tmp3_;
#line 33 "../vala-calculator.vala"
	_tmp4_ = (GtkButton*) gtk_button_new_with_label ("1");
#line 33 "../vala-calculator.vala"
	g_object_ref_sink (_tmp4_);
#line 33 "../vala-calculator.vala"
	but_1 = _tmp4_;
#line 34 "../vala-calculator.vala"
	_tmp5_ = (GtkButton*) gtk_button_new_with_label ("2");
#line 34 "../vala-calculator.vala"
	g_object_ref_sink (_tmp5_);
#line 34 "../vala-calculator.vala"
	but_2 = _tmp5_;
#line 35 "../vala-calculator.vala"
	_tmp6_ = (GtkButton*) gtk_button_new_with_label ("3");
#line 35 "../vala-calculator.vala"
	g_object_ref_sink (_tmp6_);
#line 35 "../vala-calculator.vala"
	but_3 = _tmp6_;
#line 36 "../vala-calculator.vala"
	_tmp7_ = (GtkButton*) gtk_button_new_with_label ("4");
#line 36 "../vala-calculator.vala"
	g_object_ref_sink (_tmp7_);
#line 36 "../vala-calculator.vala"
	but_4 = _tmp7_;
#line 37 "../vala-calculator.vala"
	_tmp8_ = (GtkButton*) gtk_button_new_with_label ("5");
#line 37 "../vala-calculator.vala"
	g_object_ref_sink (_tmp8_);
#line 37 "../vala-calculator.vala"
	but_5 = _tmp8_;
#line 38 "../vala-calculator.vala"
	_tmp9_ = (GtkButton*) gtk_button_new_with_label ("6");
#line 38 "../vala-calculator.vala"
	g_object_ref_sink (_tmp9_);
#line 38 "../vala-calculator.vala"
	but_6 = _tmp9_;
#line 39 "../vala-calculator.vala"
	_tmp10_ = (GtkButton*) gtk_button_new_with_label ("7");
#line 39 "../vala-calculator.vala"
	g_object_ref_sink (_tmp10_);
#line 39 "../vala-calculator.vala"
	but_7 = _tmp10_;
#line 40 "../vala-calculator.vala"
	_tmp11_ = (GtkButton*) gtk_button_new_with_label ("8");
#line 40 "../vala-calculator.vala"
	g_object_ref_sink (_tmp11_);
#line 40 "../vala-calculator.vala"
	but_8 = _tmp11_;
#line 41 "../vala-calculator.vala"
	_tmp12_ = (GtkButton*) gtk_button_new_with_label ("9");
#line 41 "../vala-calculator.vala"
	g_object_ref_sink (_tmp12_);
#line 41 "../vala-calculator.vala"
	but_9 = _tmp12_;
#line 44 "../vala-calculator.vala"
	_tmp13_ = (GtkButton*) gtk_button_new_with_label ("÷");
#line 44 "../vala-calculator.vala"
	g_object_ref_sink (_tmp13_);
#line 44 "../vala-calculator.vala"
	butDiv = _tmp13_;
#line 45 "../vala-calculator.vala"
	_tmp14_ = (GtkButton*) gtk_button_new_with_label ("×");
#line 45 "../vala-calculator.vala"
	g_object_ref_sink (_tmp14_);
#line 45 "../vala-calculator.vala"
	butMul = _tmp14_;
#line 46 "../vala-calculator.vala"
	_tmp15_ = (GtkButton*) gtk_button_new_with_label ("-");
#line 46 "../vala-calculator.vala"
	g_object_ref_sink (_tmp15_);
#line 46 "../vala-calculator.vala"
	butMinus = _tmp15_;
#line 47 "../vala-calculator.vala"
	_tmp16_ = (GtkButton*) gtk_button_new_with_label ("+");
#line 47 "../vala-calculator.vala"
	g_object_ref_sink (_tmp16_);
#line 47 "../vala-calculator.vala"
	butPlus = _tmp16_;
#line 48 "../vala-calculator.vala"
	_tmp17_ = (GtkButton*) gtk_button_new_with_label ("=");
#line 48 "../vala-calculator.vala"
	g_object_ref_sink (_tmp17_);
#line 48 "../vala-calculator.vala"
	butEqual = _tmp17_;
#line 51 "../vala-calculator.vala"
	_tmp18_ = (GtkButton*) gtk_button_new_with_label ("%");
#line 51 "../vala-calculator.vala"
	g_object_ref_sink (_tmp18_);
#line 51 "../vala-calculator.vala"
	butPercent = _tmp18_;
#line 52 "../vala-calculator.vala"
	_tmp19_ = (GtkButton*) gtk_button_new_with_label ("√");
#line 52 "../vala-calculator.vala"
	g_object_ref_sink (_tmp19_);
#line 52 "../vala-calculator.vala"
	butSqrt = _tmp19_;
#line 53 "../vala-calculator.vala"
	_tmp20_ = (GtkButton*) gtk_button_new_with_label ("±");
#line 53 "../vala-calculator.vala"
	g_object_ref_sink (_tmp20_);
#line 53 "../vala-calculator.vala"
	butSign = _tmp20_;
#line 56 "../vala-calculator.vala"
	_tmp21_ = (GtkButton*) gtk_button_new_with_label ("C");
#line 56 "../vala-calculator.vala"
	g_object_ref_sink (_tmp21_);
#line 56 "../vala-calculator.vala"
	butCls = _tmp21_;
#line 57 "../vala-calculator.vala"
	_tmp22_ = (GtkButton*) gtk_button_new_with_label (".");
#line 57 "../vala-calculator.vala"
	g_object_ref_sink (_tmp22_);
#line 57 "../vala-calculator.vala"
	butDot = _tmp22_;
#line 60 "../vala-calculator.vala"
	_tmp23_ = but_0;
#line 60 "../vala-calculator.vala"
	_tmp24_ = _g_object_ref0 (_tmp23_);
#line 60 "../vala-calculator.vala"
	_tmp25_ = but_1;
#line 60 "../vala-calculator.vala"
	_tmp26_ = _g_object_ref0 (_tmp25_);
#line 60 "../vala-calculator.vala"
	_tmp27_ = but_2;
#line 60 "../vala-calculator.vala"
	_tmp28_ = _g_object_ref0 (_tmp27_);
#line 60 "../vala-calculator.vala"
	_tmp29_ = but_3;
#line 60 "../vala-calculator.vala"
	_tmp30_ = _g_object_ref0 (_tmp29_);
#line 60 "../vala-calculator.vala"
	_tmp31_ = but_4;
#line 60 "../vala-calculator.vala"
	_tmp32_ = _g_object_ref0 (_tmp31_);
#line 60 "../vala-calculator.vala"
	_tmp33_ = but_5;
#line 60 "../vala-calculator.vala"
	_tmp34_ = _g_object_ref0 (_tmp33_);
#line 60 "../vala-calculator.vala"
	_tmp35_ = but_6;
#line 60 "../vala-calculator.vala"
	_tmp36_ = _g_object_ref0 (_tmp35_);
#line 60 "../vala-calculator.vala"
	_tmp37_ = but_7;
#line 60 "../vala-calculator.vala"
	_tmp38_ = _g_object_ref0 (_tmp37_);
#line 60 "../vala-calculator.vala"
	_tmp39_ = but_8;
#line 60 "../vala-calculator.vala"
	_tmp40_ = _g_object_ref0 (_tmp39_);
#line 60 "../vala-calculator.vala"
	_tmp41_ = but_9;
#line 60 "../vala-calculator.vala"
	_tmp42_ = _g_object_ref0 (_tmp41_);
#line 60 "../vala-calculator.vala"
	_tmp43_ = butCls;
#line 60 "../vala-calculator.vala"
	_tmp44_ = _g_object_ref0 (_tmp43_);
#line 60 "../vala-calculator.vala"
	_tmp45_ = butPercent;
#line 60 "../vala-calculator.vala"
	_tmp46_ = _g_object_ref0 (_tmp45_);
#line 60 "../vala-calculator.vala"
	_tmp47_ = butSqrt;
#line 60 "../vala-calculator.vala"
	_tmp48_ = _g_object_ref0 (_tmp47_);
#line 60 "../vala-calculator.vala"
	_tmp49_ = butDiv;
#line 60 "../vala-calculator.vala"
	_tmp50_ = _g_object_ref0 (_tmp49_);
#line 60 "../vala-calculator.vala"
	_tmp51_ = butMul;
#line 60 "../vala-calculator.vala"
	_tmp52_ = _g_object_ref0 (_tmp51_);
#line 60 "../vala-calculator.vala"
	_tmp53_ = butMinus;
#line 60 "../vala-calculator.vala"
	_tmp54_ = _g_object_ref0 (_tmp53_);
#line 60 "../vala-calculator.vala"
	_tmp55_ = butPlus;
#line 60 "../vala-calculator.vala"
	_tmp56_ = _g_object_ref0 (_tmp55_);
#line 60 "../vala-calculator.vala"
	_tmp57_ = butEqual;
#line 60 "../vala-calculator.vala"
	_tmp58_ = _g_object_ref0 (_tmp57_);
#line 60 "../vala-calculator.vala"
	_tmp59_ = butDot;
#line 60 "../vala-calculator.vala"
	_tmp60_ = _g_object_ref0 (_tmp59_);
#line 60 "../vala-calculator.vala"
	_tmp61_ = butSign;
#line 60 "../vala-calculator.vala"
	_tmp62_ = _g_object_ref0 (_tmp61_);
#line 60 "../vala-calculator.vala"
	_tmp63_ = g_new0 (GtkButton*, 20 + 1);
#line 60 "../vala-calculator.vala"
	_tmp63_[0] = _tmp24_;
#line 60 "../vala-calculator.vala"
	_tmp63_[1] = _tmp26_;
#line 60 "../vala-calculator.vala"
	_tmp63_[2] = _tmp28_;
#line 60 "../vala-calculator.vala"
	_tmp63_[3] = _tmp30_;
#line 60 "../vala-calculator.vala"
	_tmp63_[4] = _tmp32_;
#line 60 "../vala-calculator.vala"
	_tmp63_[5] = _tmp34_;
#line 60 "../vala-calculator.vala"
	_tmp63_[6] = _tmp36_;
#line 60 "../vala-calculator.vala"
	_tmp63_[7] = _tmp38_;
#line 60 "../vala-calculator.vala"
	_tmp63_[8] = _tmp40_;
#line 60 "../vala-calculator.vala"
	_tmp63_[9] = _tmp42_;
#line 60 "../vala-calculator.vala"
	_tmp63_[10] = _tmp44_;
#line 60 "../vala-calculator.vala"
	_tmp63_[11] = _tmp46_;
#line 60 "../vala-calculator.vala"
	_tmp63_[12] = _tmp48_;
#line 60 "../vala-calculator.vala"
	_tmp63_[13] = _tmp50_;
#line 60 "../vala-calculator.vala"
	_tmp63_[14] = _tmp52_;
#line 60 "../vala-calculator.vala"
	_tmp63_[15] = _tmp54_;
#line 60 "../vala-calculator.vala"
	_tmp63_[16] = _tmp56_;
#line 60 "../vala-calculator.vala"
	_tmp63_[17] = _tmp58_;
#line 60 "../vala-calculator.vala"
	_tmp63_[18] = _tmp60_;
#line 60 "../vala-calculator.vala"
	_tmp63_[19] = _tmp62_;
#line 60 "../vala-calculator.vala"
	list_button = _tmp63_;
#line 60 "../vala-calculator.vala"
	list_button_length1 = 20;
#line 60 "../vala-calculator.vala"
	_list_button_size_ = list_button_length1;
#line 64 "../vala-calculator.vala"
	_tmp64_ = list_button;
#line 64 "../vala-calculator.vala"
	_tmp64__length1 = list_button_length1;
#line 510 "vala-calculator.c"
	{
		GtkButton** button_collection = NULL;
		gint button_collection_length1 = 0;
		gint _button_collection_size_ = 0;
		gint button_it = 0;
#line 64 "../vala-calculator.vala"
		button_collection = _tmp64_;
#line 64 "../vala-calculator.vala"
		button_collection_length1 = _tmp64__length1;
#line 64 "../vala-calculator.vala"
		for (button_it = 0; button_it < button_collection_length1; button_it = button_it + 1) {
#line 522 "vala-calculator.c"
			GtkButton* _tmp65_;
			GtkButton* button = NULL;
#line 64 "../vala-calculator.vala"
			_tmp65_ = _g_object_ref0 (button_collection[button_it]);
#line 64 "../vala-calculator.vala"
			button = _tmp65_;
#line 529 "vala-calculator.c"
			{
				GtkButton* _tmp66_;
#line 65 "../vala-calculator.vala"
				_tmp66_ = button;
#line 65 "../vala-calculator.vala"
				g_signal_connect_object (_tmp66_, "clicked", (GCallback) _my_calc_on_clicked_gtk_button_clicked, self, 0);
#line 64 "../vala-calculator.vala"
				_g_object_unref0 (button);
#line 538 "vala-calculator.c"
			}
		}
	}
#line 69 "../vala-calculator.vala"
	_tmp67_ = (GtkGrid*) gtk_grid_new ();
#line 69 "../vala-calculator.vala"
	g_object_ref_sink (_tmp67_);
#line 69 "../vala-calculator.vala"
	grid = _tmp67_;
#line 70 "../vala-calculator.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) grid);
#line 72 "../vala-calculator.vala"
	_tmp68_ = self->priv->entDisp;
#line 72 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp68_, 0, 0, 4, 1);
#line 74 "../vala-calculator.vala"
	_tmp69_ = butCls;
#line 74 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp69_, 0, 1, 1, 1);
#line 75 "../vala-calculator.vala"
	_tmp70_ = butPercent;
#line 75 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp70_, 1, 1, 1, 1);
#line 76 "../vala-calculator.vala"
	_tmp71_ = butSqrt;
#line 76 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp71_, 2, 1, 1, 1);
#line 77 "../vala-calculator.vala"
	_tmp72_ = butDiv;
#line 77 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp72_, 3, 1, 1, 1);
#line 79 "../vala-calculator.vala"
	_tmp73_ = but_7;
#line 79 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp73_, 0, 2, 1, 1);
#line 80 "../vala-calculator.vala"
	_tmp74_ = but_8;
#line 80 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp74_, 1, 2, 1, 1);
#line 81 "../vala-calculator.vala"
	_tmp75_ = but_9;
#line 81 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp75_, 2, 2, 1, 1);
#line 82 "../vala-calculator.vala"
	_tmp76_ = butMul;
#line 82 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp76_, 3, 2, 1, 1);
#line 84 "../vala-calculator.vala"
	_tmp77_ = but_4;
#line 84 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp77_, 0, 3, 1, 1);
#line 85 "../vala-calculator.vala"
	_tmp78_ = but_5;
#line 85 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp78_, 1, 3, 1, 1);
#line 86 "../vala-calculator.vala"
	_tmp79_ = but_6;
#line 86 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp79_, 2, 3, 1, 1);
#line 87 "../vala-calculator.vala"
	_tmp80_ = butMinus;
#line 87 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp80_, 3, 3, 1, 1);
#line 89 "../vala-calculator.vala"
	_tmp81_ = but_1;
#line 89 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp81_, 0, 4, 1, 1);
#line 90 "../vala-calculator.vala"
	_tmp82_ = but_2;
#line 90 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp82_, 1, 4, 1, 1);
#line 91 "../vala-calculator.vala"
	_tmp83_ = but_3;
#line 91 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp83_, 2, 4, 1, 1);
#line 92 "../vala-calculator.vala"
	_tmp84_ = butPlus;
#line 92 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp84_, 3, 4, 1, 1);
#line 94 "../vala-calculator.vala"
	_tmp85_ = but_0;
#line 94 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp85_, 0, 5, 1, 1);
#line 95 "../vala-calculator.vala"
	_tmp86_ = butDot;
#line 95 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp86_, 1, 5, 1, 1);
#line 96 "../vala-calculator.vala"
	_tmp87_ = butSign;
#line 96 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp87_, 2, 5, 1, 1);
#line 97 "../vala-calculator.vala"
	_tmp88_ = butEqual;
#line 97 "../vala-calculator.vala"
	gtk_grid_attach (grid, (GtkWidget*) _tmp88_, 3, 5, 1, 1);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (grid);
#line 18 "../vala-calculator.vala"
	list_button = (_vala_array_free (list_button, list_button_length1, (GDestroyNotify) g_object_unref), NULL);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butDot);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butCls);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butSign);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butSqrt);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butPercent);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butEqual);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butPlus);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butMinus);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butMul);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (butDiv);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_9);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_8);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_7);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_6);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_5);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_4);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_3);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_2);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_1);
#line 18 "../vala-calculator.vala"
	_g_object_unref0 (but_0);
#line 18 "../vala-calculator.vala"
	return self;
#line 680 "vala-calculator.c"
}

MyCalc*
my_calc_new (void)
{
#line 18 "../vala-calculator.vala"
	return my_calc_construct (TYPE_MY_CALC);
#line 688 "vala-calculator.c"
}

static void
my_calc_on_clicked (MyCalc* self,
                    GtkButton* button)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GQuark _tmp3_ = 0U;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label0 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label1 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label2 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label3 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label4 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label5 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label6 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label7 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label8 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label9 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label10 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label11 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label12 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label13 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label14 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label15 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label16 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label17 = 0;
#line 108 "../vala-calculator.vala"
	static GQuark _tmp2_label18 = 0;
#line 106 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 106 "../vala-calculator.vala"
	g_return_if_fail (button != NULL);
#line 108 "../vala-calculator.vala"
	_tmp0_ = gtk_button_get_label (button);
#line 108 "../vala-calculator.vala"
	_tmp1_ = _tmp0_;
#line 108 "../vala-calculator.vala"
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
#line 108 "../vala-calculator.vala"
	if ((((((((((_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("0")))) || (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("1"))))) || (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("2"))))) || (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("3"))))) || (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string ("4"))))) || (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string ("5"))))) || (_tmp3_ == ((0 != _tmp2_label6) ? _tmp2_label6 : (_tmp2_label6 = g_quark_from_static_string ("6"))))) || (_tmp3_ == ((0 != _tmp2_label7) ? _tmp2_label7 : (_tmp2_label7 = g_quark_from_static_string ("7"))))) || (_tmp3_ == ((0 != _tmp2_label8) ? _tmp2_label8 : (_tmp2_label8 = g_quark_from_static_string ("8"))))) || (_tmp3_ == ((0 != _tmp2_label9) ? _tmp2_label9 : (_tmp2_label9 = g_quark_from_static_string ("9"))))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 750 "vala-calculator.c"
			default:
			{
				const gchar* _tmp4_;
#line 119 "../vala-calculator.vala"
				_tmp4_ = gtk_button_get_label (button);
#line 119 "../vala-calculator.vala"
				my_calc_doApp (self, _tmp4_);
#line 120 "../vala-calculator.vala"
				break;
#line 760 "vala-calculator.c"
			}
		}
	} else if ((((_tmp3_ == ((0 != _tmp2_label10) ? _tmp2_label10 : (_tmp2_label10 = g_quark_from_static_string ("+")))) || (_tmp3_ == ((0 != _tmp2_label11) ? _tmp2_label11 : (_tmp2_label11 = g_quark_from_static_string ("-"))))) || (_tmp3_ == ((0 != _tmp2_label12) ? _tmp2_label12 : (_tmp2_label12 = g_quark_from_static_string ("×"))))) || (_tmp3_ == ((0 != _tmp2_label13) ? _tmp2_label13 : (_tmp2_label13 = g_quark_from_static_string ("÷"))))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 766 "vala-calculator.c"
			default:
			{
				const gchar* _tmp5_;
#line 125 "../vala-calculator.vala"
				_tmp5_ = gtk_button_get_label (button);
#line 125 "../vala-calculator.vala"
				my_calc_doOpe (self, _tmp5_);
#line 126 "../vala-calculator.vala"
				break;
#line 776 "vala-calculator.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label14) ? _tmp2_label14 : (_tmp2_label14 = g_quark_from_static_string (".")))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 782 "vala-calculator.c"
			default:
			{
#line 128 "../vala-calculator.vala"
				my_calc_doDot (self);
#line 129 "../vala-calculator.vala"
				break;
#line 789 "vala-calculator.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label15) ? _tmp2_label15 : (_tmp2_label15 = g_quark_from_static_string ("±")))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 795 "vala-calculator.c"
			default:
			{
#line 131 "../vala-calculator.vala"
				my_calc_doSign (self);
#line 132 "../vala-calculator.vala"
				break;
#line 802 "vala-calculator.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label16) ? _tmp2_label16 : (_tmp2_label16 = g_quark_from_static_string ("√")))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 808 "vala-calculator.c"
			default:
			{
#line 134 "../vala-calculator.vala"
				my_calc_doSqrt (self);
#line 135 "../vala-calculator.vala"
				break;
#line 815 "vala-calculator.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label17) ? _tmp2_label17 : (_tmp2_label17 = g_quark_from_static_string ("=")))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 821 "vala-calculator.c"
			default:
			{
#line 137 "../vala-calculator.vala"
				my_calc_doEqual (self);
#line 138 "../vala-calculator.vala"
				break;
#line 828 "vala-calculator.c"
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label18) ? _tmp2_label18 : (_tmp2_label18 = g_quark_from_static_string ("C")))) {
#line 108 "../vala-calculator.vala"
		switch (0) {
#line 834 "vala-calculator.c"
			default:
			{
#line 140 "../vala-calculator.vala"
				my_calc_doClear (self);
#line 141 "../vala-calculator.vala"
				break;
#line 841 "vala-calculator.c"
			}
		}
	}
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gchar* _tmp0_;
	gboolean result = FALSE;
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, FALSE);
#line 1530 "glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, FALSE);
#line 1531 "glib-2.0.vapi"
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
#line 1531 "glib-2.0.vapi"
	result = _tmp0_ != NULL;
#line 1531 "glib-2.0.vapi"
	return result;
#line 863 "vala-calculator.c"
}

static void
my_calc_disp (MyCalc* self,
              const gchar* what)
{
	gchar* dispStr = NULL;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	GtkEntry* _tmp4_;
	const gchar* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
#line 151 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 151 "../vala-calculator.vala"
	g_return_if_fail (what != NULL);
#line 154 "../vala-calculator.vala"
	if (!string_contains (what, ".")) {
#line 883 "vala-calculator.c"
		gchar* _tmp0_;
#line 155 "../vala-calculator.vala"
		_tmp0_ = g_strconcat (what, ".", NULL);
#line 155 "../vala-calculator.vala"
		_g_free0 (dispStr);
#line 155 "../vala-calculator.vala"
		dispStr = _tmp0_;
#line 891 "vala-calculator.c"
	} else {
		gchar* _tmp1_;
#line 157 "../vala-calculator.vala"
		_tmp1_ = g_strdup (what);
#line 157 "../vala-calculator.vala"
		_g_free0 (dispStr);
#line 157 "../vala-calculator.vala"
		dispStr = _tmp1_;
#line 900 "vala-calculator.c"
	}
#line 160 "../vala-calculator.vala"
	_tmp2_ = self->priv->entDisp;
#line 160 "../vala-calculator.vala"
	_tmp3_ = dispStr;
#line 160 "../vala-calculator.vala"
	gtk_entry_set_text (_tmp2_, _tmp3_);
#line 161 "../vala-calculator.vala"
	_tmp4_ = self->priv->entDisp;
#line 161 "../vala-calculator.vala"
	_tmp5_ = dispStr;
#line 161 "../vala-calculator.vala"
	_tmp6_ = strlen (_tmp5_);
#line 161 "../vala-calculator.vala"
	_tmp7_ = _tmp6_;
#line 161 "../vala-calculator.vala"
	gtk_editable_set_position ((GtkEditable*) _tmp4_, _tmp7_);
#line 151 "../vala-calculator.vala"
	_g_free0 (dispStr);
#line 920 "vala-calculator.c"
}

static gunichar
string_get_char (const gchar* self,
                 glong index)
{
	gunichar result = 0U;
#line 1262 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0U);
#line 1263 "glib-2.0.vapi"
	result = g_utf8_get_char (((gchar*) self) + index);
#line 1263 "glib-2.0.vapi"
	return result;
#line 934 "vala-calculator.c"
}

static glong
string_strnlen (gchar* str,
                glong maxlen)
{
	gchar* end = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	glong result = 0L;
#line 1447 "glib-2.0.vapi"
	_tmp0_ = memchr (str, 0, (gsize) maxlen);
#line 1447 "glib-2.0.vapi"
	end = _tmp0_;
#line 1448 "glib-2.0.vapi"
	_tmp1_ = end;
#line 1448 "glib-2.0.vapi"
	if (_tmp1_ == NULL) {
#line 1449 "glib-2.0.vapi"
		result = maxlen;
#line 1449 "glib-2.0.vapi"
		return result;
#line 957 "vala-calculator.c"
	} else {
		gchar* _tmp2_;
#line 1451 "glib-2.0.vapi"
		_tmp2_ = end;
#line 1451 "glib-2.0.vapi"
		result = (glong) (_tmp2_ - str);
#line 1451 "glib-2.0.vapi"
		return result;
#line 966 "vala-calculator.c"
	}
}

static gchar*
string_substring (const gchar* self,
                  glong offset,
                  glong len)
{
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	gchar* _tmp3_;
	gchar* result = NULL;
#line 1458 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1460 "glib-2.0.vapi"
	if (offset >= ((glong) 0)) {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = len >= ((glong) 0);
#line 985 "vala-calculator.c"
	} else {
#line 1460 "glib-2.0.vapi"
		_tmp0_ = FALSE;
#line 989 "vala-calculator.c"
	}
#line 1460 "glib-2.0.vapi"
	if (_tmp0_) {
#line 1462 "glib-2.0.vapi"
		string_length = string_strnlen ((gchar*) self, offset + len);
#line 995 "vala-calculator.c"
	} else {
		gint _tmp1_;
		gint _tmp2_;
#line 1464 "glib-2.0.vapi"
		_tmp1_ = strlen (self);
#line 1464 "glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1464 "glib-2.0.vapi"
		string_length = (glong) _tmp2_;
#line 1005 "vala-calculator.c"
	}
#line 1467 "glib-2.0.vapi"
	if (offset < ((glong) 0)) {
#line 1468 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1469 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= ((glong) 0), NULL);
#line 1013 "vala-calculator.c"
	} else {
#line 1471 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 1017 "vala-calculator.c"
	}
#line 1473 "glib-2.0.vapi"
	if (len < ((glong) 0)) {
#line 1474 "glib-2.0.vapi"
		len = string_length - offset;
#line 1023 "vala-calculator.c"
	}
#line 1476 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1477 "glib-2.0.vapi"
	_tmp3_ = g_strndup (((gchar*) self) + offset, (gsize) len);
#line 1477 "glib-2.0.vapi"
	result = _tmp3_;
#line 1477 "glib-2.0.vapi"
	return result;
#line 1033 "vala-calculator.c"
}

static void
my_calc_doApp (MyCalc* self,
               const gchar* what)
{
	const gchar* _tmp2_;
	gboolean _tmp4_ = FALSE;
#line 170 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 170 "../vala-calculator.vala"
	g_return_if_fail (what != NULL);
#line 171 "../vala-calculator.vala"
	if (!self->priv->flag_entrystarted) {
#line 1048 "vala-calculator.c"
		gchar* _tmp0_;
		const gchar* _tmp1_;
#line 172 "../vala-calculator.vala"
		_tmp0_ = g_strdup ("0.");
#line 172 "../vala-calculator.vala"
		_g_free0 (self->priv->entry);
#line 172 "../vala-calculator.vala"
		self->priv->entry = _tmp0_;
#line 173 "../vala-calculator.vala"
		_tmp1_ = self->priv->entry;
#line 173 "../vala-calculator.vala"
		my_calc_disp (self, _tmp1_);
#line 1061 "vala-calculator.c"
	}
#line 175 "../vala-calculator.vala"
	_tmp2_ = self->priv->operation;
#line 175 "../vala-calculator.vala"
	if (_tmp2_ == NULL) {
#line 1067 "vala-calculator.c"
		gchar* _tmp3_;
#line 176 "../vala-calculator.vala"
		_tmp3_ = g_strdup ("0.");
#line 176 "../vala-calculator.vala"
		_g_free0 (self->priv->result);
#line 176 "../vala-calculator.vala"
		self->priv->result = _tmp3_;
#line 1075 "vala-calculator.c"
	}
#line 178 "../vala-calculator.vala"
	if (g_strcmp0 (what, "0") == 0) {
#line 1079 "vala-calculator.c"
		const gchar* _tmp5_;
#line 178 "../vala-calculator.vala"
		_tmp5_ = self->priv->entry;
#line 178 "../vala-calculator.vala"
		_tmp4_ = g_strcmp0 (_tmp5_, "0.") == 0;
#line 1085 "vala-calculator.c"
	} else {
#line 178 "../vala-calculator.vala"
		_tmp4_ = FALSE;
#line 1089 "vala-calculator.c"
	}
#line 178 "../vala-calculator.vala"
	if (!_tmp4_) {
#line 179 "../vala-calculator.vala"
		self->priv->flag_entrystarted = TRUE;
#line 180 "../vala-calculator.vala"
		if (self->priv->flag_dot == TRUE) {
#line 1097 "vala-calculator.c"
			const gchar* _tmp6_;
			gchar* _tmp7_;
			const gchar* _tmp8_;
#line 181 "../vala-calculator.vala"
			_tmp6_ = self->priv->entry;
#line 181 "../vala-calculator.vala"
			_tmp7_ = g_strconcat (_tmp6_, what, NULL);
#line 181 "../vala-calculator.vala"
			_g_free0 (self->priv->entry);
#line 181 "../vala-calculator.vala"
			self->priv->entry = _tmp7_;
#line 182 "../vala-calculator.vala"
			_tmp8_ = self->priv->entry;
#line 182 "../vala-calculator.vala"
			my_calc_disp (self, _tmp8_);
#line 1113 "vala-calculator.c"
		} else {
			const gchar* _tmp9_;
#line 184 "../vala-calculator.vala"
			_tmp9_ = self->priv->entry;
#line 184 "../vala-calculator.vala"
			if (g_strcmp0 (_tmp9_, "0.") == 0) {
#line 1120 "vala-calculator.c"
				gchar* _tmp10_;
				const gchar* _tmp11_;
#line 185 "../vala-calculator.vala"
				_tmp10_ = g_strconcat (what, ".", NULL);
#line 185 "../vala-calculator.vala"
				_g_free0 (self->priv->entry);
#line 185 "../vala-calculator.vala"
				self->priv->entry = _tmp10_;
#line 186 "../vala-calculator.vala"
				_tmp11_ = self->priv->entry;
#line 186 "../vala-calculator.vala"
				my_calc_disp (self, _tmp11_);
#line 1133 "vala-calculator.c"
			} else {
				gint n = 0;
				const gchar* _tmp12_;
				gint _tmp13_;
				gint _tmp14_;
				const gchar* _tmp15_;
				const gchar* _tmp18_;
				gchar* _tmp19_;
				gchar* _tmp20_;
				gchar* _tmp21_;
				const gchar* _tmp22_;
#line 188 "../vala-calculator.vala"
				_tmp12_ = self->priv->entry;
#line 188 "../vala-calculator.vala"
				_tmp13_ = strlen (_tmp12_);
#line 188 "../vala-calculator.vala"
				_tmp14_ = _tmp13_;
#line 188 "../vala-calculator.vala"
				n = _tmp14_;
#line 189 "../vala-calculator.vala"
				_tmp15_ = self->priv->entry;
#line 189 "../vala-calculator.vala"
				if (string_get_char (_tmp15_, (glong) (n - 1)) == ((gunichar) '.')) {
#line 1157 "vala-calculator.c"
					const gchar* _tmp16_;
					gchar* _tmp17_;
#line 190 "../vala-calculator.vala"
					_tmp16_ = self->priv->entry;
#line 190 "../vala-calculator.vala"
					_tmp17_ = string_substring (_tmp16_, (glong) 0, (glong) (n - 1));
#line 190 "../vala-calculator.vala"
					_g_free0 (self->priv->entry);
#line 190 "../vala-calculator.vala"
					self->priv->entry = _tmp17_;
#line 1168 "vala-calculator.c"
				}
#line 192 "../vala-calculator.vala"
				_tmp18_ = self->priv->entry;
#line 192 "../vala-calculator.vala"
				_tmp19_ = g_strconcat (_tmp18_, what, NULL);
#line 192 "../vala-calculator.vala"
				_tmp20_ = _tmp19_;
#line 192 "../vala-calculator.vala"
				_tmp21_ = g_strconcat (_tmp20_, ".", NULL);
#line 192 "../vala-calculator.vala"
				_g_free0 (self->priv->entry);
#line 192 "../vala-calculator.vala"
				self->priv->entry = _tmp21_;
#line 192 "../vala-calculator.vala"
				_g_free0 (_tmp20_);
#line 193 "../vala-calculator.vala"
				_tmp22_ = self->priv->entry;
#line 193 "../vala-calculator.vala"
				my_calc_disp (self, _tmp22_);
#line 1188 "vala-calculator.c"
			}
		}
	}
}

static void
my_calc_doClear (MyCalc* self)
{
	gchar* _tmp1_;
	const gchar* _tmp2_;
#line 202 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 203 "../vala-calculator.vala"
	if (!self->priv->flag_entrystarted) {
#line 1203 "vala-calculator.c"
		gchar* _tmp0_;
#line 204 "../vala-calculator.vala"
		_tmp0_ = g_strdup ("0.");
#line 204 "../vala-calculator.vala"
		_g_free0 (self->priv->result);
#line 204 "../vala-calculator.vala"
		self->priv->result = _tmp0_;
#line 205 "../vala-calculator.vala"
		_g_free0 (self->priv->operation);
#line 205 "../vala-calculator.vala"
		self->priv->operation = NULL;
#line 1215 "vala-calculator.c"
	} else {
#line 207 "../vala-calculator.vala"
		self->priv->flag_entrystarted = FALSE;
#line 1219 "vala-calculator.c"
	}
#line 210 "../vala-calculator.vala"
	self->priv->flag_dot = FALSE;
#line 212 "../vala-calculator.vala"
	_tmp1_ = g_strdup ("0.");
#line 212 "../vala-calculator.vala"
	_g_free0 (self->priv->entry);
#line 212 "../vala-calculator.vala"
	self->priv->entry = _tmp1_;
#line 213 "../vala-calculator.vala"
	_tmp2_ = self->priv->entry;
#line 213 "../vala-calculator.vala"
	my_calc_disp (self, _tmp2_);
#line 1233 "vala-calculator.c"
}

static void
my_calc_doDot (MyCalc* self)
{
#line 219 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 220 "../vala-calculator.vala"
	self->priv->flag_dot = TRUE;
#line 1243 "vala-calculator.c"
}

static gfloat
float_parse (const gchar* str)
{
	gfloat result = 0.0F;
#line 913 "glib-2.0.vapi"
	g_return_val_if_fail (str != NULL, 0.0F);
#line 914 "glib-2.0.vapi"
	result = strtof (str, NULL);
#line 914 "glib-2.0.vapi"
	return result;
#line 1256 "vala-calculator.c"
}

static void
my_calc_doEqual (MyCalc* self)
{
	const gchar* _tmp0_;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	const gchar* _tmp21_;
#line 226 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 227 "../vala-calculator.vala"
	_tmp0_ = self->priv->operation;
#line 227 "../vala-calculator.vala"
	if (_tmp0_ != NULL) {
#line 1272 "vala-calculator.c"
		const gchar* _tmp1_;
		const gchar* _tmp2_;
		GQuark _tmp4_ = 0U;
#line 228 "../vala-calculator.vala"
		static GQuark _tmp3_label0 = 0;
#line 228 "../vala-calculator.vala"
		static GQuark _tmp3_label1 = 0;
#line 228 "../vala-calculator.vala"
		static GQuark _tmp3_label2 = 0;
#line 228 "../vala-calculator.vala"
		static GQuark _tmp3_label3 = 0;
#line 228 "../vala-calculator.vala"
		_tmp1_ = self->priv->operation;
#line 228 "../vala-calculator.vala"
		_tmp2_ = _tmp1_;
#line 228 "../vala-calculator.vala"
		_tmp4_ = (NULL == _tmp2_) ? 0 : g_quark_from_string (_tmp2_);
#line 228 "../vala-calculator.vala"
		if (_tmp4_ == ((0 != _tmp3_label0) ? _tmp3_label0 : (_tmp3_label0 = g_quark_from_static_string ("+")))) {
#line 228 "../vala-calculator.vala"
			switch (0) {
#line 1294 "vala-calculator.c"
				default:
				{
					const gchar* _tmp5_;
					const gchar* _tmp6_;
					gchar* _tmp7_;
#line 230 "../vala-calculator.vala"
					_tmp5_ = self->priv->result;
#line 230 "../vala-calculator.vala"
					_tmp6_ = self->priv->entry;
#line 230 "../vala-calculator.vala"
					_tmp7_ = g_strdup_printf ("%g", float_parse (_tmp5_) + float_parse (_tmp6_));
#line 230 "../vala-calculator.vala"
					_g_free0 (self->priv->result);
#line 230 "../vala-calculator.vala"
					self->priv->result = _tmp7_;
#line 231 "../vala-calculator.vala"
					break;
#line 1312 "vala-calculator.c"
				}
			}
		} else if (_tmp4_ == ((0 != _tmp3_label1) ? _tmp3_label1 : (_tmp3_label1 = g_quark_from_static_string ("-")))) {
#line 228 "../vala-calculator.vala"
			switch (0) {
#line 1318 "vala-calculator.c"
				default:
				{
					const gchar* _tmp8_;
					const gchar* _tmp9_;
					gchar* _tmp10_;
#line 233 "../vala-calculator.vala"
					_tmp8_ = self->priv->result;
#line 233 "../vala-calculator.vala"
					_tmp9_ = self->priv->entry;
#line 233 "../vala-calculator.vala"
					_tmp10_ = g_strdup_printf ("%g", float_parse (_tmp8_) - float_parse (_tmp9_));
#line 233 "../vala-calculator.vala"
					_g_free0 (self->priv->result);
#line 233 "../vala-calculator.vala"
					self->priv->result = _tmp10_;
#line 234 "../vala-calculator.vala"
					break;
#line 1336 "vala-calculator.c"
				}
			}
		} else if (_tmp4_ == ((0 != _tmp3_label2) ? _tmp3_label2 : (_tmp3_label2 = g_quark_from_static_string ("×")))) {
#line 228 "../vala-calculator.vala"
			switch (0) {
#line 1342 "vala-calculator.c"
				default:
				{
					const gchar* _tmp11_;
					const gchar* _tmp12_;
					gchar* _tmp13_;
#line 236 "../vala-calculator.vala"
					_tmp11_ = self->priv->result;
#line 236 "../vala-calculator.vala"
					_tmp12_ = self->priv->entry;
#line 236 "../vala-calculator.vala"
					_tmp13_ = g_strdup_printf ("%g", float_parse (_tmp11_) * float_parse (_tmp12_));
#line 236 "../vala-calculator.vala"
					_g_free0 (self->priv->result);
#line 236 "../vala-calculator.vala"
					self->priv->result = _tmp13_;
#line 237 "../vala-calculator.vala"
					break;
#line 1360 "vala-calculator.c"
				}
			}
		} else if (_tmp4_ == ((0 != _tmp3_label3) ? _tmp3_label3 : (_tmp3_label3 = g_quark_from_static_string ("÷")))) {
#line 228 "../vala-calculator.vala"
			switch (0) {
#line 1366 "vala-calculator.c"
				default:
				{
					const gchar* _tmp14_;
					const gchar* _tmp15_;
					gchar* _tmp16_;
#line 239 "../vala-calculator.vala"
					_tmp14_ = self->priv->result;
#line 239 "../vala-calculator.vala"
					_tmp15_ = self->priv->entry;
#line 239 "../vala-calculator.vala"
					_tmp16_ = g_strdup_printf ("%g", float_parse (_tmp14_) / float_parse (_tmp15_));
#line 239 "../vala-calculator.vala"
					_g_free0 (self->priv->result);
#line 239 "../vala-calculator.vala"
					self->priv->result = _tmp16_;
#line 240 "../vala-calculator.vala"
					break;
#line 1384 "vala-calculator.c"
				}
			}
		}
	} else {
		const gchar* _tmp17_;
		gchar* _tmp18_;
#line 243 "../vala-calculator.vala"
		_tmp17_ = self->priv->entry;
#line 243 "../vala-calculator.vala"
		_tmp18_ = g_strdup (_tmp17_);
#line 243 "../vala-calculator.vala"
		_g_free0 (self->priv->result);
#line 243 "../vala-calculator.vala"
		self->priv->result = _tmp18_;
#line 1399 "vala-calculator.c"
	}
#line 245 "../vala-calculator.vala"
	self->priv->flag_entrystarted = FALSE;
#line 246 "../vala-calculator.vala"
	_g_free0 (self->priv->operation);
#line 246 "../vala-calculator.vala"
	self->priv->operation = NULL;
#line 247 "../vala-calculator.vala"
	self->priv->flag_dot = FALSE;
#line 249 "../vala-calculator.vala"
	_tmp19_ = self->priv->result;
#line 249 "../vala-calculator.vala"
	_tmp20_ = g_strdup (_tmp19_);
#line 249 "../vala-calculator.vala"
	_g_free0 (self->priv->entry);
#line 249 "../vala-calculator.vala"
	self->priv->entry = _tmp20_;
#line 250 "../vala-calculator.vala"
	_tmp21_ = self->priv->entry;
#line 250 "../vala-calculator.vala"
	my_calc_disp (self, _tmp21_);
#line 1421 "vala-calculator.c"
}

static void
my_calc_doOpe (MyCalc* self,
               const gchar* what)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
#line 259 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 259 "../vala-calculator.vala"
	g_return_if_fail (what != NULL);
#line 260 "../vala-calculator.vala"
	_tmp0_ = self->priv->operation;
#line 260 "../vala-calculator.vala"
	if (_tmp0_ != NULL) {
#line 260 "../vala-calculator.vala"
		my_calc_doEqual (self);
#line 1442 "vala-calculator.c"
	}
#line 261 "../vala-calculator.vala"
	_tmp1_ = g_strdup (what);
#line 261 "../vala-calculator.vala"
	_g_free0 (self->priv->operation);
#line 261 "../vala-calculator.vala"
	self->priv->operation = _tmp1_;
#line 262 "../vala-calculator.vala"
	self->priv->flag_entrystarted = FALSE;
#line 263 "../vala-calculator.vala"
	self->priv->flag_dot = FALSE;
#line 265 "../vala-calculator.vala"
	_tmp2_ = self->priv->entry;
#line 265 "../vala-calculator.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 265 "../vala-calculator.vala"
	_g_free0 (self->priv->result);
#line 265 "../vala-calculator.vala"
	self->priv->result = _tmp3_;
#line 1462 "vala-calculator.c"
}

static void
my_calc_doSign (MyCalc* self)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
#line 271 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 272 "../vala-calculator.vala"
	self->priv->flag_entrystarted = FALSE;
#line 273 "../vala-calculator.vala"
	_tmp0_ = self->priv->entry;
#line 273 "../vala-calculator.vala"
	_tmp1_ = g_strdup_printf ("%g", -1 * float_parse (_tmp0_));
#line 273 "../vala-calculator.vala"
	_g_free0 (self->priv->entry);
#line 273 "../vala-calculator.vala"
	self->priv->entry = _tmp1_;
#line 274 "../vala-calculator.vala"
	_tmp2_ = self->priv->entry;
#line 274 "../vala-calculator.vala"
	my_calc_disp (self, _tmp2_);
#line 1487 "vala-calculator.c"
}

static gchar*
double_to_string (gdouble self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gint _tmp1__length1;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* result = NULL;
#line 989 "glib-2.0.vapi"
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
#line 989 "glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 989 "glib-2.0.vapi"
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
#line 989 "glib-2.0.vapi"
	_tmp2_ = g_ascii_dtostr (_tmp1_, (gint) G_ASCII_DTOSTR_BUF_SIZE, self);
#line 989 "glib-2.0.vapi"
	_tmp3_ = g_strdup (_tmp2_);
#line 989 "glib-2.0.vapi"
	_tmp4_ = _tmp3_;
#line 989 "glib-2.0.vapi"
	_tmp1_ = (g_free (_tmp1_), NULL);
#line 989 "glib-2.0.vapi"
	result = _tmp4_;
#line 989 "glib-2.0.vapi"
	return result;
#line 1518 "vala-calculator.c"
}

static void
my_calc_doSqrt (MyCalc* self)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
#line 280 "../vala-calculator.vala"
	g_return_if_fail (self != NULL);
#line 281 "../vala-calculator.vala"
	self->priv->flag_entrystarted = FALSE;
#line 282 "../vala-calculator.vala"
	_tmp0_ = self->priv->entry;
#line 282 "../vala-calculator.vala"
	_tmp1_ = double_to_string (sqrt ((gdouble) float_parse (_tmp0_)));
#line 282 "../vala-calculator.vala"
	_g_free0 (self->priv->entry);
#line 282 "../vala-calculator.vala"
	self->priv->entry = _tmp1_;
#line 283 "../vala-calculator.vala"
	_tmp2_ = self->priv->entry;
#line 283 "../vala-calculator.vala"
	my_calc_disp (self, _tmp2_);
#line 1543 "vala-calculator.c"
}

static void
my_calc_class_init (MyCalcClass * klass,
                    gpointer klass_data)
{
#line 3 "../vala-calculator.vala"
	my_calc_parent_class = g_type_class_peek_parent (klass);
#line 3 "../vala-calculator.vala"
	g_type_class_adjust_private_offset (klass, &MyCalc_private_offset);
#line 3 "../vala-calculator.vala"
	G_OBJECT_CLASS (klass)->finalize = my_calc_finalize;
#line 1556 "vala-calculator.c"
}

static void
my_calc_instance_init (MyCalc * self,
                       gpointer klass)
{
	GtkEntry* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
#line 3 "../vala-calculator.vala"
	self->priv = my_calc_get_instance_private (self);
#line 6 "../vala-calculator.vala"
	_tmp0_ = (GtkEntry*) gtk_entry_new ();
#line 6 "../vala-calculator.vala"
	g_object_ref_sink (_tmp0_);
#line 6 "../vala-calculator.vala"
	self->priv->entDisp = _tmp0_;
#line 8 "../vala-calculator.vala"
	self->priv->flag_dot = FALSE;
#line 9 "../vala-calculator.vala"
	self->priv->flag_entrystarted = FALSE;
#line 11 "../vala-calculator.vala"
	_tmp1_ = g_strdup ("");
#line 11 "../vala-calculator.vala"
	self->priv->entry = _tmp1_;
#line 12 "../vala-calculator.vala"
	_tmp2_ = g_strdup ("");
#line 12 "../vala-calculator.vala"
	self->priv->result = _tmp2_;
#line 13 "../vala-calculator.vala"
	_tmp3_ = g_strdup ("");
#line 13 "../vala-calculator.vala"
	self->priv->operation = _tmp3_;
#line 1591 "vala-calculator.c"
}

static void
my_calc_finalize (GObject * obj)
{
	MyCalc * self;
#line 3 "../vala-calculator.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MY_CALC, MyCalc);
#line 6 "../vala-calculator.vala"
	_g_object_unref0 (self->priv->entDisp);
#line 11 "../vala-calculator.vala"
	_g_free0 (self->priv->entry);
#line 12 "../vala-calculator.vala"
	_g_free0 (self->priv->result);
#line 13 "../vala-calculator.vala"
	_g_free0 (self->priv->operation);
#line 3 "../vala-calculator.vala"
	G_OBJECT_CLASS (my_calc_parent_class)->finalize (obj);
#line 1610 "vala-calculator.c"
}

static GType
my_calc_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (MyCalcClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) my_calc_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MyCalc), 0, (GInstanceInitFunc) my_calc_instance_init, NULL };
	GType my_calc_type_id;
	my_calc_type_id = g_type_register_static (gtk_window_get_type (), "MyCalc", &g_define_type_info, 0);
	MyCalc_private_offset = g_type_add_instance_private (my_calc_type_id, sizeof (MyCalcPrivate));
	return my_calc_type_id;
}

GType
my_calc_get_type (void)
{
	static volatile gsize my_calc_type_id__volatile = 0;
	if (g_once_init_enter (&my_calc_type_id__volatile)) {
		GType my_calc_type_id;
		my_calc_type_id = my_calc_get_type_once ();
		g_once_init_leave (&my_calc_type_id__volatile, my_calc_type_id);
	}
	return my_calc_type_id__volatile;
}

gint
_vala_main (gchar** args,
            gint args_length1)
{
	MyCalc* app = NULL;
	MyCalc* _tmp0_;
	gint result = 0;
#line 291 "../vala-calculator.vala"
	gtk_init ((gint*) (&args_length1), &args);
#line 293 "../vala-calculator.vala"
	_tmp0_ = my_calc_new ();
#line 293 "../vala-calculator.vala"
	g_object_ref_sink (_tmp0_);
#line 293 "../vala-calculator.vala"
	app = _tmp0_;
#line 294 "../vala-calculator.vala"
	gtk_widget_show_all ((GtkWidget*) app);
#line 295 "../vala-calculator.vala"
	gtk_main ();
#line 296 "../vala-calculator.vala"
	result = 0;
#line 296 "../vala-calculator.vala"
	_g_object_unref0 (app);
#line 296 "../vala-calculator.vala"
	return result;
#line 1660 "vala-calculator.c"
}

int
main (int argc,
      char ** argv)
{
#line 290 "../vala-calculator.vala"
	return _vala_main (argv, argc);
#line 1669 "vala-calculator.c"
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

